[passwords]
HOD_PASSWORD = "hodsecure"

[teacher_passwords]
Graph_Theory = "gt123"
Compiler_Construction = "cc123"
Parallel_and_Distributed_Computing = "pdc123"
Mobile_Application_Development = "mad123"
Web_Technology = "wt123"
Modeling_and_Simulation = "ms123"
Enterprise_System = "es123"
System_and_Network_Administration = "sna123"
Information_Security = "is123"
Internet_of_Things = "iot123"
Computer_Vision = "cv123"
Digital_Image_Processing = "dip123"
Entrepreneurship_and_Leadership_Skills = "els123"
Linear_Algebra = "la123"
Operating_System = "os123"
Software_Engineering = "se123"
Artificial_Intelligence = "ai123"
Computer_Organization_and_Assembly_Languages = "coal123"
Theory_of_Automata = "toa123"
DLD = "dld123"
OOP = "oop123"
Pakistan_Studies = "ps123"
Data_Structures = "ds123"
Mathematical_Foundation_II = "mf123"
Islamic_Studies = "islamic123"
Relevance_of_Sufism_and_Modern_Sciences = "sufism123"
